name: Build Package Index

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup git
        run: |
          git config --global user.email "bot@hydroroll.team"
          git config --global user.name "HydroRollBot"

      - name: build pkg Index
        run: make pkg_index

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: "feat(site): update index for ${{ github.ref_name }} [skip ci]"
